### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by Eric-C-Lee** [Shi-AE/sgmis#2]
![image](https://github.com/Shi-AE/sgmis/assets/166688856/846dab3f-499d-4065-80a6-8fbf60927e80)
![image](https://github.com/Shi-AE/sgmis/assets/166688856/5a976b94-0bb1-4365-a8f6-1ca6c9fd64a3)

**Comment by Shi-AE** [comment]
前后端分离，需要启动前端，前端是 vit  + vue。进入v-dev/sgmis文件夹，执行 `npm install` 和 `npm run dev`

**Comment by Shi-AE** [comment]
> ![image](https://private-user-images.githubusercontent.com/166688856/337300816-846dab3f-499d-4065-80a6-8fbf60927e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTY2OTgsIm5iZiI6MTcxNzg1NjM5OCwicGF0aCI6Ii8xNjY2ODg4NTYvMzM3MzAwODE2LTg0NmRhYjNmLTQ5OWQtNDA2NS04MGE2LThmYmY2MDkyN2U4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNDE5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGRkODc2ZDk3MDEwNGY2M2VhODk2OTc4YWU2OWY2MjhiYmM1MTVmMWVhMjE2MzIxMzFlMjBmY2YzNWE5M2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gR9NhPLQCoSY6TmhU5INHPtSroG5mu_4OTRBCBJKGbY) ![image](https://private-user-images.githubusercontent.com/166688856/337300911-5a976b94-0bb1-4365-a8f6-1ca6c9fd64a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTY2OTgsIm5iZiI6MTcxNzg1NjM5OCwicGF0aCI6Ii8xNjY2ODg4NTYvMzM3MzAwOTExLTVhOTc2Yjk0LTBiYjEtNDM2NS1hOGY2LTFjYTZjOWZkNjRhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNDE5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjcxNGE4OWJlZGYxODdkNmJlODM3OGM3YWM1Y2U5MGJmYmE1ZDhjZGUyMTc3NTdhZDU4MjFlYjBlNDI4OTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2tTZJFNm_eLsoSlxsyxVptZAPozKFd2jeWAmYzsIeLE)

前后端分离，需要启动前端，前端是 vite + vue。进入v-dev/sgmis文件夹，执行 npm install 和 npm run dev

**Comment by Shi-AE** [comment]
在之前更新中应该是给了登录表单的默认值
account：root
password：admin123


密码使用`Argon2`算法加密，依赖第三方库`org.bouncycastle`
加密配置位于`application.yml`中
``` yml
encrypt:
  memoryPowOfTwo: 13
  iterations: 9
  parallelism: 5
  hashLength: 512
```
由于将参数设置过高，执行速度较慢，可自行调整参数，调整参数后需**重新创建用户**
可以在测试类中通过这段代码创建用户
```java
@SpringBootTest
public class AdminTest {

    @Autowired
    private UserService userService;
    @Autowired
    private EncryptUtil encryptUtil;

    @Test
    void add() {
        String account = "user123";
        String password = "123456";
        Boolean admin = true;
        User user = User
                .builder()
                .account(account)
                .password(password.getBytes())
                .admin(admin)
                .gid(IdWorker.getId())
                .build();
        encryptUtil.passwordEncrypt(user);
        System.out.println(user);
        userService.save(user);
    }
}
```
![image](https://github.com/Shi-AE/sgmis/assets/111409670/0312e8e5-8981-4b7a-8ff1-b699d9aa4cb5)

**Comment by Shi-AE** [comment]
> 蟹蟹，现在能用了，不过还有个疑惑，sql里insert到t_user表的那些数据(在我这里显示为乱码)，是本身的加密么，我在前端用root 123456，后端提示密码不对

在之前更新中应该是给了登录表单的默认值
account：root
password：admin123


密码使用`Argon2`算法加密，依赖第三方库`org.bouncycastle`
加密配置位于`application.yml`中
``` yml
encrypt:
  memoryPowOfTwo: 13
  iterations: 9
  parallelism: 5
  hashLength: 512
```
由于将参数设置过高，执行速度较慢，可自行调整参数，调整参数后需**重新创建用户**
可以在测试类中通过这段代码创建用户
```java
@SpringBootTest
public class AdminTest {

    @Autowired
    private UserService userService;
    @Autowired
    private EncryptUtil encryptUtil;

    @Test
    void add() {
        String account = "user123";
        String password = "123456";
        Boolean admin = true;
        User user = User
                .builder()
                .account(account)
                .password(password.getBytes())
                .admin(admin)
                .gid(IdWorker.getId())
                .build();
        encryptUtil.passwordEncrypt(user);
        System.out.println(user);
        userService.save(user);
    }
}
```
![image](https://github.com/Shi-AE/sgmis/assets/111409670/0312e8e5-8981-4b7a-8ff1-b699d9aa4cb5)
